import mongoose from 'mongoose';

// Defines the structure of a single message within the chat session
const MessageSchema = new mongoose.Schema({
    role: { // 'user' or 'model'
        type: String,
        required: true,
        enum: ['user', 'model']
    },
    content: { // The text of the message
        type: String,
        required: true
    },
    timestamp: {
        type: Date,
        default: Date.now
    }
}, { _id: false }); // Prevents Mongoose from adding redundant IDs to sub-documents

// Defines the structure of the entire chat session
const ChatSchema = new mongoose.Schema({
    sessionId: { // The unique ID generated by the frontend
        type: String,
        required: true,
        unique: true
    },
    messages: [MessageSchema], // Array of all messages
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
}, { timestamps: true }); // Mongoose handles 'createdAt' and 'updatedAt' fields automatically

const Chat = mongoose.model('Chat', ChatSchema);

export default Chat;